name: Send Crypto Signal

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam
  workflow_dispatch:

jobs:
  send-signal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios technicalindicators

      - name: Run Signal Bot
        run: node sendSignal.js
